use std::str::FromStr;
use ast::OneValue;
use ast;

grammar;

pub Function : (OneValue, ast::Block) = <name:Atom> "{" <b:Block> "}" => (name, b);

pub Block : ast::Block = <l: Token*> => ast::Block { items : l };

pub Token : ast::Token = {
    "if" => ast::Token::If,
    "return" => ast::Token::Return,
    <v: Atom> => ast::Token::Call(v)
};

pub Atom : OneValue = <s:r"[a-zA-Z][a-zA-Z0-9_]*"> => OneValue::from_string(s);
